name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
    
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN  }}